//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPC_BOM.Mouser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.mouser.com/service", ConfigurationName="Mouser.SearchAPISoap")]
    public interface SearchAPISoap {
        
        // CODEGEN: Generating message contract since message SearchByKeywordRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/SearchByKeyword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPC_BOM.Mouser.SearchByKeywordResponse SearchByKeyword(GPC_BOM.Mouser.SearchByKeywordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/SearchByKeyword", ReplyAction="*")]
        System.Threading.Tasks.Task<GPC_BOM.Mouser.SearchByKeywordResponse> SearchByKeywordAsync(GPC_BOM.Mouser.SearchByKeywordRequest request);
        
        // CODEGEN: Generating message contract since message SearchByPartNumberRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/SearchByPartNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPC_BOM.Mouser.SearchByPartNumberResponse SearchByPartNumber(GPC_BOM.Mouser.SearchByPartNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/SearchByPartNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<GPC_BOM.Mouser.SearchByPartNumberResponse> SearchByPartNumberAsync(GPC_BOM.Mouser.SearchByPartNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/GetPartsForMouserPartNumberAndCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GPC_BOM.Mouser.MouserProductList GetPartsForMouserPartNumberAndCountry(string internalKey, string mouserPartNumbers, string delimiter, string countryCode, string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/GetPartsForMouserPartNumberAndCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<GPC_BOM.Mouser.MouserProductList> GetPartsForMouserPartNumberAndCountryAsync(string internalKey, string mouserPartNumbers, string delimiter, string countryCode, string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/ServiceStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/ServiceStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceStatusAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AccountInfo accountInfoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountInfo AccountInfo {
            get {
                return this.accountInfoField;
            }
            set {
                this.accountInfoField = value;
                this.RaisePropertyChanged("AccountInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class AccountInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partnerIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
                this.RaisePropertyChanged("PartnerID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserProduct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string manufacturerPartNumberField;
        
        private string manufacturerField;
        
        private decimal unitPriceField;
        
        private string productDetailsURLField;
        
        private int stockField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ManufacturerPartNumber {
            get {
                return this.manufacturerPartNumberField;
            }
            set {
                this.manufacturerPartNumberField = value;
                this.RaisePropertyChanged("ManufacturerPartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("UnitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProductDetailsURL {
            get {
                return this.productDetailsURLField;
            }
            set {
                this.productDetailsURLField = value;
                this.RaisePropertyChanged("ProductDetailsURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("Stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserProductList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MouserProduct[] productField;
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Product", Order=0)]
        public MouserProduct[] Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("Product");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class UnitWeightKg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> unitWeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> UnitWeight {
            get {
                return this.unitWeightField;
            }
            set {
                this.unitWeightField = value;
                this.RaisePropertyChanged("UnitWeight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class AlternatePackaging : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aPMfrPNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string APMfrPN {
            get {
                return this.aPMfrPNField;
            }
            set {
                this.aPMfrPNField = value;
                this.RaisePropertyChanged("APMfrPN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pricebreaks2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class Pricebreaks : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int quantityField;
        
        private string priceField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class Pricebreaks2 : Pricebreaks {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class ProductAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("AttributeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AttributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
                this.RaisePropertyChanged("AttributeValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string availabilityField;
        
        private string dataSheetUrlField;
        
        private string descriptionField;
        
        private string imagePathField;
        
        private string categoryField;
        
        private string leadTimeField;
        
        private string lifecycleStatusField;
        
        private string manufacturerField;
        
        private string manufacturerPartNumberField;
        
        private string minField;
        
        private string multField;
        
        private string mouserPartNumberField;
        
        private ProductAttribute[] productAttributesField;
        
        private Pricebreaks[] priceBreaksField;
        
        private AlternatePackaging[] alternatePackagingsField;
        
        private string productDetailUrlField;
        
        private bool reelingField;
        
        private string rOHSStatusField;
        
        private string suggestedReplacementField;
        
        private int multiSimBlueField;
        
        private UnitWeightKg unitWeightKgField;
        
        private string restrictionMessageField;
        
        private string pIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
                this.RaisePropertyChanged("Availability");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DataSheetUrl {
            get {
                return this.dataSheetUrlField;
            }
            set {
                this.dataSheetUrlField = value;
                this.RaisePropertyChanged("DataSheetUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImagePath {
            get {
                return this.imagePathField;
            }
            set {
                this.imagePathField = value;
                this.RaisePropertyChanged("ImagePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LeadTime {
            get {
                return this.leadTimeField;
            }
            set {
                this.leadTimeField = value;
                this.RaisePropertyChanged("LeadTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LifecycleStatus {
            get {
                return this.lifecycleStatusField;
            }
            set {
                this.lifecycleStatusField = value;
                this.RaisePropertyChanged("LifecycleStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ManufacturerPartNumber {
            get {
                return this.manufacturerPartNumberField;
            }
            set {
                this.manufacturerPartNumberField = value;
                this.RaisePropertyChanged("ManufacturerPartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Mult {
            get {
                return this.multField;
            }
            set {
                this.multField = value;
                this.RaisePropertyChanged("Mult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MouserPartNumber {
            get {
                return this.mouserPartNumberField;
            }
            set {
                this.mouserPartNumberField = value;
                this.RaisePropertyChanged("MouserPartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public ProductAttribute[] ProductAttributes {
            get {
                return this.productAttributesField;
            }
            set {
                this.productAttributesField = value;
                this.RaisePropertyChanged("ProductAttributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public Pricebreaks[] PriceBreaks {
            get {
                return this.priceBreaksField;
            }
            set {
                this.priceBreaksField = value;
                this.RaisePropertyChanged("PriceBreaks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public AlternatePackaging[] AlternatePackagings {
            get {
                return this.alternatePackagingsField;
            }
            set {
                this.alternatePackagingsField = value;
                this.RaisePropertyChanged("AlternatePackagings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ProductDetailUrl {
            get {
                return this.productDetailUrlField;
            }
            set {
                this.productDetailUrlField = value;
                this.RaisePropertyChanged("ProductDetailUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool Reeling {
            get {
                return this.reelingField;
            }
            set {
                this.reelingField = value;
                this.RaisePropertyChanged("Reeling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ROHSStatus {
            get {
                return this.rOHSStatusField;
            }
            set {
                this.rOHSStatusField = value;
                this.RaisePropertyChanged("ROHSStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string SuggestedReplacement {
            get {
                return this.suggestedReplacementField;
            }
            set {
                this.suggestedReplacementField = value;
                this.RaisePropertyChanged("SuggestedReplacement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int MultiSimBlue {
            get {
                return this.multiSimBlueField;
            }
            set {
                this.multiSimBlueField = value;
                this.RaisePropertyChanged("MultiSimBlue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public UnitWeightKg UnitWeightKg {
            get {
                return this.unitWeightKgField;
            }
            set {
                this.unitWeightKgField = value;
                this.RaisePropertyChanged("UnitWeightKg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string RestrictionMessage {
            get {
                return this.restrictionMessageField;
            }
            set {
                this.restrictionMessageField = value;
                this.RaisePropertyChanged("RestrictionMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
                this.RaisePropertyChanged("PID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class ResultParts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numberOfResultField;
        
        private MouserPart[] partsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumberOfResult {
            get {
                return this.numberOfResultField;
            }
            set {
                this.numberOfResultField = value;
                this.RaisePropertyChanged("NumberOfResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public MouserPart[] Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByKeyword", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class SearchByKeywordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.mouser.com/service")]
        public GPC_BOM.Mouser.MouserHeader MouserHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public string keyword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=1)]
        public int records;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=2)]
        public int startingRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string searchOptions;
        
        public SearchByKeywordRequest() {
        }
        
        public SearchByKeywordRequest(GPC_BOM.Mouser.MouserHeader MouserHeader, string keyword, int records, int startingRecord, string searchOptions) {
            this.MouserHeader = MouserHeader;
            this.keyword = keyword;
            this.records = records;
            this.startingRecord = startingRecord;
            this.searchOptions = searchOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByKeywordResponse", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class SearchByKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public GPC_BOM.Mouser.ResultParts SearchByKeywordResult;
        
        public SearchByKeywordResponse() {
        }
        
        public SearchByKeywordResponse(GPC_BOM.Mouser.ResultParts SearchByKeywordResult) {
            this.SearchByKeywordResult = SearchByKeywordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByPartNumber", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class SearchByPartNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.mouser.com/service")]
        public GPC_BOM.Mouser.MouserHeader MouserHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public string mouserPartNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string partSearchOptions;
        
        public SearchByPartNumberRequest() {
        }
        
        public SearchByPartNumberRequest(GPC_BOM.Mouser.MouserHeader MouserHeader, string mouserPartNumber, string partSearchOptions) {
            this.MouserHeader = MouserHeader;
            this.mouserPartNumber = mouserPartNumber;
            this.partSearchOptions = partSearchOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByPartNumberResponse", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class SearchByPartNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public GPC_BOM.Mouser.ResultParts SearchByPartNumberResult;
        
        public SearchByPartNumberResponse() {
        }
        
        public SearchByPartNumberResponse(GPC_BOM.Mouser.ResultParts SearchByPartNumberResult) {
            this.SearchByPartNumberResult = SearchByPartNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchAPISoapChannel : GPC_BOM.Mouser.SearchAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchAPISoapClient : System.ServiceModel.ClientBase<GPC_BOM.Mouser.SearchAPISoap>, GPC_BOM.Mouser.SearchAPISoap {
        
        public SearchAPISoapClient() {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPC_BOM.Mouser.SearchByKeywordResponse GPC_BOM.Mouser.SearchAPISoap.SearchByKeyword(GPC_BOM.Mouser.SearchByKeywordRequest request) {
            return base.Channel.SearchByKeyword(request);
        }
        
        public GPC_BOM.Mouser.ResultParts SearchByKeyword(GPC_BOM.Mouser.MouserHeader MouserHeader, string keyword, int records, int startingRecord, string searchOptions) {
            GPC_BOM.Mouser.SearchByKeywordRequest inValue = new GPC_BOM.Mouser.SearchByKeywordRequest();
            inValue.MouserHeader = MouserHeader;
            inValue.keyword = keyword;
            inValue.records = records;
            inValue.startingRecord = startingRecord;
            inValue.searchOptions = searchOptions;
            GPC_BOM.Mouser.SearchByKeywordResponse retVal = ((GPC_BOM.Mouser.SearchAPISoap)(this)).SearchByKeyword(inValue);
            return retVal.SearchByKeywordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPC_BOM.Mouser.SearchByKeywordResponse> GPC_BOM.Mouser.SearchAPISoap.SearchByKeywordAsync(GPC_BOM.Mouser.SearchByKeywordRequest request) {
            return base.Channel.SearchByKeywordAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPC_BOM.Mouser.SearchByKeywordResponse> SearchByKeywordAsync(GPC_BOM.Mouser.MouserHeader MouserHeader, string keyword, int records, int startingRecord, string searchOptions) {
            GPC_BOM.Mouser.SearchByKeywordRequest inValue = new GPC_BOM.Mouser.SearchByKeywordRequest();
            inValue.MouserHeader = MouserHeader;
            inValue.keyword = keyword;
            inValue.records = records;
            inValue.startingRecord = startingRecord;
            inValue.searchOptions = searchOptions;
            return ((GPC_BOM.Mouser.SearchAPISoap)(this)).SearchByKeywordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPC_BOM.Mouser.SearchByPartNumberResponse GPC_BOM.Mouser.SearchAPISoap.SearchByPartNumber(GPC_BOM.Mouser.SearchByPartNumberRequest request) {
            return base.Channel.SearchByPartNumber(request);
        }
        
        public GPC_BOM.Mouser.ResultParts SearchByPartNumber(GPC_BOM.Mouser.MouserHeader MouserHeader, string mouserPartNumber, string partSearchOptions) {
            GPC_BOM.Mouser.SearchByPartNumberRequest inValue = new GPC_BOM.Mouser.SearchByPartNumberRequest();
            inValue.MouserHeader = MouserHeader;
            inValue.mouserPartNumber = mouserPartNumber;
            inValue.partSearchOptions = partSearchOptions;
            GPC_BOM.Mouser.SearchByPartNumberResponse retVal = ((GPC_BOM.Mouser.SearchAPISoap)(this)).SearchByPartNumber(inValue);
            return retVal.SearchByPartNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GPC_BOM.Mouser.SearchByPartNumberResponse> GPC_BOM.Mouser.SearchAPISoap.SearchByPartNumberAsync(GPC_BOM.Mouser.SearchByPartNumberRequest request) {
            return base.Channel.SearchByPartNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<GPC_BOM.Mouser.SearchByPartNumberResponse> SearchByPartNumberAsync(GPC_BOM.Mouser.MouserHeader MouserHeader, string mouserPartNumber, string partSearchOptions) {
            GPC_BOM.Mouser.SearchByPartNumberRequest inValue = new GPC_BOM.Mouser.SearchByPartNumberRequest();
            inValue.MouserHeader = MouserHeader;
            inValue.mouserPartNumber = mouserPartNumber;
            inValue.partSearchOptions = partSearchOptions;
            return ((GPC_BOM.Mouser.SearchAPISoap)(this)).SearchByPartNumberAsync(inValue);
        }
        
        public GPC_BOM.Mouser.MouserProductList GetPartsForMouserPartNumberAndCountry(string internalKey, string mouserPartNumbers, string delimiter, string countryCode, string currencyCode) {
            return base.Channel.GetPartsForMouserPartNumberAndCountry(internalKey, mouserPartNumbers, delimiter, countryCode, currencyCode);
        }
        
        public System.Threading.Tasks.Task<GPC_BOM.Mouser.MouserProductList> GetPartsForMouserPartNumberAndCountryAsync(string internalKey, string mouserPartNumbers, string delimiter, string countryCode, string currencyCode) {
            return base.Channel.GetPartsForMouserPartNumberAndCountryAsync(internalKey, mouserPartNumbers, delimiter, countryCode, currencyCode);
        }
        
        public bool ServiceStatus() {
            return base.Channel.ServiceStatus();
        }
        
        public System.Threading.Tasks.Task<bool> ServiceStatusAsync() {
            return base.Channel.ServiceStatusAsync();
        }
    }
}
